<Project>

  <PropertyGroup>
    <Datestamp>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd"))</Datestamp>
    <Timestamp>$([System.DateTime]::UtcNow.ToString("yyyy-MM-ddHHmm"))</Timestamp>
    <Authors>David Hary</Authors>
    <Owners>Integrated Scientific Resources</Owners>
    <Company>isr.cc</Company>
    <Copyright>(c) 2022 Integrated Scientific Resources, Inc. All rights reserved.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
  </PropertyGroup>

</Project>
