<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>preview</LangVersion>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Assembly Info -->
    <RootNamespace>cc.isr.VXI11</RootNamespace>
    <AssemblyName>cc.isr.VXI11.Server</AssemblyName>
    <ApplicationTitle>cc.isr.VXI11.Server</ApplicationTitle>
    <ApplicationId>cc.isr.vxi11.server</ApplicationId>

    <!-- Coding -->
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>On</OptionStrict>
    <OptionInfer>Off</OptionInfer>

    <!-- Signature -->
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\items\keyPair.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>

    <!-- NuGet -->
    <IsPackable>true</IsPackable>
    <PackageId>cc.isr.VXI11.Client</PackageId>
    <Description>A pure C# implementation of VXI-11 servers, instruments and interfaces.</Description>
    <PackageTags>VXI-11 Client</PackageTags>
    <PackageOutputPath>C:\my\nuget</PackageOutputPath>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <!-- Documentation -->
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>

  </PropertyGroup>

  <!-- Assembly attributes -->
  <ItemGroup>
    <AssemblyAttribute Include="System.CLSCompliantAttribute">
      <_Parameter1>true</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.InteropServices.ComVisibleAttribute">
      <_Parameter1>false</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\vxi\cc.isr.VXI11.csproj" />
  </ItemGroup>

</Project>
