 <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>preview</LangVersion>

    <OutputType>Exe</OutputType>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Assembly Info -->
    <RootNamespace>cc.isr.VXI11.ClientTester</RootNamespace>
    <AssemblyName>cc.isr.VXI11.ClientTester</AssemblyName>
    <ApplicationTitle>cc.isr.VXI11.ClientTester</ApplicationTitle>
    <ApplicationId>cc.isr.vxi11.ClientTester</ApplicationId>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\vxi\client\cc.isr.VXI11.Client.csproj" />
  </ItemGroup>

</Project>
