<Project>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);TRACE;PROJREF_;PACK_;GitHub;</DefineConstants>
  </PropertyGroup>

  <Import Project="c:\my\lib\vs\core\ide\src\my\lib\vs\directory.build.props" />

<!-- imported from c:\my\lib\vs\core\ide\src\my\lib\vs\directory.build.props

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <NuGetAudit>true</NuGetAudit>
    <WaningsNotAsErrors>NU1900;NU1901;NU1802</WaningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-5crp-9r3c-p9vr" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SourceLink.Copy.PdbFiles" Version="2.8 .3" PrivateAssets="All" />
  </ItemGroup>
 
  <PropertyGroup Condition="$(DefineConstants.Contains(';PACK;'))" >
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup Condition="$(DefineConstants.Contains(';PACK;GitHub;'))" >
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0 .203" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="$(DefineConstants.Contains(';PACK;GitHub_;'))" >
    <PackageReference Include="Microsoft.SourceLink.Bitbucket.Git" Version="10.0 .203" PrivateAssets="All" />
  </ItemGroup>

-->

  <PropertyGroup Condition="$(DefineConstants.Contains(';GitHub;'))" >
    <GitRepositoryRemoteName>hub</GitRepositoryRemoteName>
    <PackageProjectUrl>https://github.com/AteCoder/dn.vxi11</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Condition="$(DefineConstants.Contains(';GitHub_;'))" >
    <GitRepositoryRemoteName>origin</GitRepositoryRemoteName>
    <PackageProjectUrl>https://bitbucket.org/davidhary/dn.vxi11</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Label="BasePath">
    <!-- This fixed missing property when using from dotnet cli -->
    <SolutionDir Condition="'$(SolutionDir)'==''">$(MSBuildThisFileDirectory)..\..\</SolutionDir>
  </PropertyGroup>
  
  <PropertyGroup>
    <Datestamp>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd"))</Datestamp>
    <Timestamp>$([System.DateTime]::UtcNow.ToString("yyyy-MM-ddHHmm"))</Timestamp>
    <Authors>David Hary</Authors>
    <Owners>Integrated Scientific Resources</Owners>
    <Company>isr.cc</Company>
    <Copyright>(c) 2022 Integrated Scientific Resources, Inc. All rights reserved.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <PropertyGroup>
    <!-- NuGet -->
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>ms-icon-70x70.png</PackageIcon>
    <PackageOutputDir>..\..\.nuget\artifacts</PackageOutputDir>
    <PackageOwners>Integrated Scientific Resources, Inc.</PackageOwners>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\items\ms-icon-70x70.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
  
  <Import Project="items\version.build.props" />

</Project>

